apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Raygun Exception Handler
  description: Raygun Exception Handler plugin and support for the Reekoh IoT Platform
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Logger
  price: 0
  tags:
    - logger
    - exception-logger
    - raygun

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      apiKey:
        label: API Key
        type: Password
        required: true
        help: Please specify your Raygun.io API key
        maxLength: 1000